# fly.toml app configuration file generated for mlm-app-jhc on 2025-02-09T05:24:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mlm-app-jhc'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
